var subtitles = [
  "is this a minecraft reference?",
  "a simple discord.js bot",
  "a bot with a ton of commands",
  "hey vsauce, micheal here",
  "Party? more like... eh forget it...",
  "some neat bot",
  "i wonder who writes this things",
  "well yes but actually no",
  "1% sugar!",
  "100% pure!",
  "12 herbs and spices!",
  "12345 is a bad password!",
  "150 bpm for 400000 minutes!",
  "150% hyperbole!",
  "Absolutely no memes!",
  "A skeleton popped out!",
  "An illusion! What are you hiding?",
  "Any computer is a laptop if you're brave enough!",
  "As seen on TV!",
  "Ask your doctor!",
  "As seen on TV!",
  "Bread is pain!",
  "Bringing home the bacon!",
  "Ceci n'est pas une sous-titre!",
  "Check it out!",
  "Classy!",
  "Cloud computing!",
  "Also try MEE6!",
  "Also try Dyno!",
  "Déjà vu!",
  "Déjà vu!",
  "Do you want to join my server?",
  "Don't bother with the clones!",
  "Don't look directly at the bugs!",
  "Don’t worry, be happy!",
  "doot doot",
  "Feature packed!",
  "Fat free!",
  "I need more context.",
  "idspispopd!",
  "if not ok then return end",
  "Information wants to be free!",
  "In case it isn't obvious, bots aren't peoples.",
  "It came from space.",
  "It's groundbreaking!",
  "Legal in Finland!",
  "Limited edition!",
  "Super new mini power nintendo 23dsi lite light micro xl ddl e uboy virtual advance pocket sp player & knuckles color cube 64 & watch entertainment system featuring dante from the devil may cry series also plays on 2ds!",
  "MEMES, MEMES EVERYWHERE",
  "Make me a table, a funky table!",
  "MAP11 has two names!",
  "Matt Damon!",
  "May contain nuts!",
  "Mmmph, mmph!",
  "Nice to meet you!",
  "Now contains 32 random daily cats!",
  "Oh man!",
  "Peter Griffin!",
  "Play him off, keyboard cat!",
  "Plz reply to my tweet!",
  "pls rt",
  "Random splash!",
  "Run, coward! I hunger!",
  "So fresh, so clean!",
  "Something funny!",
  "Something's not quite right...",
  "So sweet, like a nice bon bon!",
  "sqrt(-1) love you!",
  "stonks",
  "Stay a while and listen!",
  "Strange, but not a stranger!",
  "Supercalifragilisticexpialidocious!",
  "That's no moon!",
  "The user is a spy!",
  "This is my true form!",
  "+100 sentences",
  "Throw a blanket over it!",
  "Throw yourself at the ground and miss",
  "Tip your waiter!",
  "Try it!",
  "You have a 1 out of 100 chance of seeing this message!",
  "Ultimate edition!",
  "Uninflammable!",
  "Une baguette!",
  "Vote for net neutrality!",
  "Welcome to your Doom!",
  "Water proof!",
  "Discord is neat",
  "	You're going too fast!",
  "You've got a brand new key!",
  "never gonna give you up!",
  "Γεια σου Ελλάδα!",
  "Привет Россия!",
  "日本ハロー！",
  "한국 안녕하세요!",
  "你好中国！",
  "I swear this website will get hijaked",
  "Hello",
  "Oh, hi",
  "Damn",
  "i h8 gramar erorrs"
]





window.onload = function what(){
  var a = subtitles[ Math.floor( Math.random() * subtitles.length)];
  document.getElementById("subtitle").innerHTML = '"' + a + '"';
}

